version: "3.6"
services:
  frontend:
    build: ./frontend
    ports:
    - 5000:5000
    environment:
    - API_URL=http://localhost:8000
  backend:
    build: ./backend
    ports:
    - 8000:8000
    volumes:
    - ./logs:/app/logs
    environment:
    - FRONT_URL=http://localhost:5000
    - REDIS=redis
    - DB_HOST=db
    - DB_NAME=db_31
    - DB_USERNAME=user_31
    - DB_PASSWORD=83CON6NDazpJ700D2xu2GpXnu6PZpZTYDqjGuoKwJ7zd58F4P0
    depends_on:
    - redis
    - db
  redis:
    image: redis:alpine
  db:
    image: postgres:alpine
    environment:
    - POSTGRES_PASSWORD=83CON6NDazpJ700D2xu2GpXnu6PZpZTYDqjGuoKwJ7zd58F4P0
    - POSTGRES_DB=db_31
    - POSTGRES_USER=user_31
